import { sha1Hex } from './crypto';

export interface CloudinaryConfig {
  cloudName: string;
  apiKey: string;
  apiSecret: string;
}

/**
 * Cloudinary's signature formula (their spec): take every param EXCEPT
 * file/api_key/resource_type, sort keys alphabetically, join as
 * "key=value&key2=value2", append the api secret directly (no separator),
 * then SHA-1 hex. This part is standard and documented — safe to rely on.
 */
async function signParams(params: Record<string, string | number>, apiSecret: string): Promise<string> {
  const sorted = Object.keys(params)
    .sort()
    .map((key) => `${key}=${params[key]}`)
    .join('&');
  return sha1Hex(sorted + apiSecret);
}

/**
 * For the BROWSER to upload a KYC photo directly to Cloudinary.
 * The frontend POSTs the file + these fields as multipart/form-data to
 * `https://api.cloudinary.com/v1_1/{cloudName}/image/upload`.
 *
 * type: 'authenticated' means the asset is NOT publicly reachable by
 * guessing the URL — this matters for PAN/Aadhaar/selfie images.
 */
export async function buildClientUploadParams(
  config: CloudinaryConfig,
  opts: { folder: string; publicId?: string }
) {
  const timestamp = Math.floor(Date.now() / 1000);
  const paramsToSign: Record<string, string | number> = {
    timestamp,
    folder: opts.folder,
    type: 'authenticated',
  };
  if (opts.publicId) paramsToSign.public_id = opts.publicId;

  const signature = await signParams(paramsToSign, config.apiSecret);

  return {
    url: `https://api.cloudinary.com/v1_1/${config.cloudName}/image/upload`,
    fields: {
      api_key: config.apiKey,
      timestamp: String(timestamp),
      signature,
      folder: opts.folder,
      type: 'authenticated',
      ...(opts.publicId ? { public_id: opts.publicId } : {}),
    },
  };
}

/**
 * For the WORKER to upload server-generated bytes (the agreement PDF).
 * Runs entirely server-side — the raw PDF bytes never go through the browser.
 */
export async function uploadBufferToCloudinary(
  config: CloudinaryConfig,
  bytes: Uint8Array,
  opts: { folder: string; publicId: string; resourceType?: 'image' | 'raw' }
): Promise<{ publicId: string; resourceType: string }> {
  const timestamp = Math.floor(Date.now() / 1000);
  const paramsToSign: Record<string, string | number> = {
    timestamp,
    folder: opts.folder,
    public_id: opts.publicId,
    type: 'authenticated',
  };
  const signature = await signParams(paramsToSign, config.apiSecret);

  const form = new FormData();
  form.append('file', new Blob([bytes], { type: 'application/pdf' }), `${opts.publicId}.pdf`);
  form.append('api_key', config.apiKey);
  form.append('timestamp', String(timestamp));
  form.append('signature', signature);
  form.append('folder', opts.folder);
  form.append('public_id', opts.publicId);
  form.append('type', 'authenticated');

  const resourceType = opts.resourceType ?? 'raw';
  const res = await fetch(`https://api.cloudinary.com/v1_1/${config.cloudName}/${resourceType}/upload`, {
    method: 'POST',
    body: form,
  });
  if (!res.ok) {
    throw new Error(`Cloudinary upload failed: ${res.status} ${await res.text()}`);
  }
  const json = await res.json<{ public_id: string; resource_type: string }>();
  return { publicId: json.public_id, resourceType: json.resource_type };
}

/**
 * ⚠️ NOT INCLUDED ON PURPOSE: a "generate a signed delivery URL for an
 * `authenticated` asset" helper.
 *
 * Cloudinary's private-delivery URL signing uses a DIFFERENT scheme than
 * the upload signature above (an auth_token/ACL system, not a simple
 * SHA-1-of-sorted-params). Hand-rolling that incorrectly is the one
 * mistake in this whole file that could look like it works while
 * actually leaving KYC documents under-protected — so rather than ship
 * a guessed implementation, wire this against Cloudinary's current
 * documented algorithm (or their official SDK under `nodejs_compat`)
 * before you let anyone view a real KYC image through this system.
 * Everything else in this file — the upload signing — is the standard,
 * documented formula and is safe to build on as-is.
 */
